spring:
  application:
    name: Esercizio10-10
  jpa:
    hibernate:
      dialect: jakarta.persistence.jdbc.url
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/db_Esercizio10_10
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver